import { AlertTriangle, Check, ChevronDown, MapPinned, Radio, Send, Thermometer, Video } from 'lucide-react'
import { Cell, Pie, PieChart, ResponsiveContainer } from 'recharts'
import { CircleMarker, MapContainer, Marker, Polygon, Polyline, Popup, TileLayer } from 'react-leaflet'
import { useParams } from 'react-router-dom'
import StatusPill from '../components/StatusPill'
import { alerts, hazards, mapCenter, mission, missions, victims } from '../data/mockMissionData'
import 'leaflet/dist/leaflet.css'

const hazardData = [{ name: 'Critical', value: 3, color: '#ef5350' }, { name: 'High', value: 4, color: '#ff9f43' }, { name: 'Moderate', value: 3, color: '#f2d14b' }, { name: 'Cleared', value: 2, color: '#43d17b' }]
const path = [[28.612, 77.216], [28.614, 77.219], [28.616, 77.223], [28.613, 77.227]] as const

function DashboardPage() {
  const { missionId } = useParams()
  const activeMission = missions.find((item) => item.name.toLowerCase().replaceAll(' ', '-') === missionId) ?? mission
  const center: [number, number] = [mapCenter.lat, mapCenter.lng]
  return <div className="dashboard-page min-h-full bg-[#202635] text-text"><div className="mx-auto max-w-[1800px] space-y-3">
    <header className="flex min-h-[62px] items-center justify-between rounded-lg border border-white/15 bg-[#4e586e] px-4 py-3"><div><div className="aero-micro text-[9px] text-white/55">Mission / active operation</div><h1 className="aero-heading mt-1 text-[26px] uppercase leading-none text-white md:text-[32px]">MISSION: {activeMission.name}</h1><div className="mt-1 text-[10px] uppercase tracking-[0.18em] text-white/70">{activeMission.disasterType} — {activeMission.owner}</div></div><div className="hidden text-right text-[10px] uppercase tracking-[0.16em] text-white/70 lg:block"><span className="text-[#86e2a4]">● SYSTEM ONLINE</span><br />ONE DRONE&nbsp; | &nbsp;MANY LIVES</div></header>
    <div className="dashboard-layout">
      <section className="panel overflow-hidden p-3"><div className="mb-3 flex items-center justify-between text-[11px] font-bold uppercase tracking-[0.16em] text-white"><span className="flex items-center gap-2"><Radio size={15} /> DRONE 1</span><StatusPill label="ACTIVE" tone="green" /></div><div className="relative h-[142px] overflow-hidden rounded-md border border-white/15 bg-[#263248]"><img src="/drone-render.png" alt="AS-01 drone" className="absolute left-[-23%] top-[-51%] w-[146%] max-w-none mix-blend-screen opacity-90" /></div><div className="mt-3 space-y-2 border-b border-white/10 pb-3 text-[10px] uppercase tracking-[0.13em] text-white/70">{[['MODEL', 'PX4 + RB5'], ['CALLSIGN', 'AS-01'], ['BATTERY', '78%'], ['FLIGHT TIME', '14:32 / 25:00'], ['ALTITUDE', '50 m'], ['SPEED', '5.2 m/s'], ['LINK', 'Strong (5G)'], ['MODE', 'Autonomous (SAR)']].map(([label, value]) => <div key={label} className="flex justify-between gap-3"><span>{label}</span><strong className="text-white">{value}</strong></div>)}</div><div className="mt-3 grid grid-cols-3 gap-1"><button type="button" className="rounded border border-[#8ae0ff]/50 bg-[#8ae0ff]/15 px-2 py-2 text-[9px] uppercase"><Video size={13} className="mx-auto mb-1" />Live feed</button><button type="button" className="rounded border border-white/15 bg-white/5 px-2 py-2 text-[9px] uppercase"><Thermometer size={13} className="mx-auto mb-1" />Thermal</button><button type="button" className="rounded border border-white/15 bg-white/5 px-2 py-2 text-[9px] uppercase">Both</button></div><div className="mt-3 grid grid-cols-2 gap-2"><img src="/disaster-landscape.png" alt="RGB disaster feed" className="h-24 w-full rounded border border-white/15 object-cover" /><img src="/disaster-landscape.png" alt="Thermal disaster feed" className="h-24 w-full rounded border border-white/15 object-cover brightness-125 saturate-[2.2] hue-rotate-[300deg]" /></div></section>
      <section className="panel min-h-[485px] overflow-hidden p-3"><div className="mb-3 flex items-center justify-between text-[11px] font-bold uppercase tracking-[0.16em] text-white"><span className="flex items-center gap-2"><MapPinned size={15} /> MAP VIEW</span><button type="button" className="flex items-center gap-2 rounded border border-white/15 bg-[#29364d] px-3 py-2 text-[9px] uppercase">Satellite view <ChevronDown size={13} /></button></div><div className="relative h-[440px] overflow-hidden rounded-md border border-white/15"><MapContainer center={center} zoom={14} style={{ height: '100%', width: '100%' }}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{victims.map((victim) => <Marker key={victim.id} position={[victim.latitude, victim.longitude]}><Popup>{victim.id} · {victim.priority}</Popup></Marker>)}{hazards.map((hazard) => <Polygon key={hazard.id} positions={hazard.coords as unknown as [number, number][]} pathOptions={{ color: hazard.severity === 'CRITICAL' ? '#ef5350' : '#ff9f43', fillColor: hazard.severity === 'CRITICAL' ? '#ef5350' : '#ff9f43', fillOpacity: 0.3, weight: 2 }} />)}<Polyline positions={path as unknown as [number, number][]} pathOptions={{ color: '#42d7c7', weight: 4, dashArray: '7 8' }} /><CircleMarker center={[28.6139, 77.2208]} radius={8} pathOptions={{ color: '#42d7c7', fillColor: '#42d7c7', fillOpacity: 1 }} /></MapContainer><div className="pointer-events-none absolute bottom-3 left-3 z-[500] rounded border border-white/20 bg-[#202b40]/90 p-3 text-[9px] uppercase leading-5 text-white/80"><strong className="text-white">LEGEND</strong><br /><span className="text-red-300">●</span> Victim P1 &nbsp; <span className="text-yellow-300">●</span> Victim P2<br /><span className="text-orange-300">■</span> Hazard &nbsp; <span className="text-cyan-300">- -</span> Drone path</div></div></section>
      <section className="panel min-h-[485px] overflow-hidden p-3"><div className="mb-3 flex items-center justify-between text-[11px] font-bold uppercase tracking-[0.16em] text-white">ALERT FEED <span className="rounded border border-white/15 px-2 py-1 text-[9px] text-white/60">{alerts.length} ACTIVE</span></div><div className="space-y-2">{alerts.slice(0, 5).map((alert) => <div key={alert.id} className="rounded-md border border-white/10 bg-[#3a465f]/65 p-2.5"><div className="flex gap-2"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded bg-red-500/20 text-red-300"><AlertTriangle size={16} /></div><div><strong className="text-[11px] uppercase text-white">{alert.title}</strong><div className="mt-1 text-[10px] text-white/60">{alert.location} · {alert.timestamp}</div><p className="mt-1 text-[10px] leading-4 text-white/75">{alert.rationale}</p></div></div></div>)}</div></section>
    </div>
    <div className="dashboard-lower"><section className="panel p-3"><div className="mb-3 text-[10px] font-bold uppercase text-white">MISSION STATUS</div>{['Takeoff', 'Survey Area', 'Detect & Map Hazards', 'Locate Survivors', 'Generate Safe Routes', 'Return to Base'].map((item, index) => <div key={item} className="flex items-center justify-between border-b border-white/10 py-2 text-[9px] uppercase text-white/70"><span className="flex items-center gap-2"><span className={`flex h-4 w-4 items-center justify-center rounded-full border ${index < 2 ? 'border-[#43d17b] text-[#43d17b]' : 'border-white/25'}`}>{index < 2 ? <Check size={10} /> : '○'}</span>{item}</span><span>{index < 2 ? 'In progress' : 'Pending'}</span></div>)}</section><section className="panel p-3"><div className="mb-3 text-[10px] font-bold uppercase text-white">TELEMETRY</div><div className="grid grid-cols-2 gap-2">{[['BATTERY', '78%'], ['ALTITUDE', '50 m'], ['SPEED', '5.2 m/s'], ['GPS', '3D FIX']].map(([label, value]) => <div key={label} className="rounded border border-white/15 bg-[#3a465f]/75 p-3"><div className="text-[9px] uppercase text-white/55">{label}</div><div className="mt-3 text-[15px] font-bold text-white">{value}</div></div>)}</div></section><section className="panel p-3"><div className="mb-2 text-[10px] font-bold uppercase text-white">HAZARD STATISTICS</div><div className="flex items-center gap-2"><div className="h-24 w-24"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={hazardData} dataKey="value" innerRadius={27} outerRadius={40} paddingAngle={3} stroke="none">{hazardData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie></PieChart></ResponsiveContainer></div><div className="space-y-1 text-[9px] uppercase text-white/70">{hazardData.map((entry) => <div key={entry.name}><span className="mr-2 inline-block h-2 w-2 rounded-full" style={{ backgroundColor: entry.color }} />{entry.name}</div>)}</div></div></section><section className="panel p-3"><div className="mb-3 text-[10px] font-bold uppercase text-white">SUGGESTED SAFE ROUTE</div><div className="relative h-20 overflow-hidden rounded border border-white/15 bg-[#29364c]"><div className="absolute inset-0 bg-[linear-gradient(145deg,transparent_48%,rgba(67,209,123,0.85)_49%,rgba(67,209,123,0.85)_51%,transparent_52%)]" /><div className="absolute bottom-2 left-3 rounded bg-[#43d17b] px-2 py-1 text-[9px] font-bold text-[#14251b]">LOW RISK</div></div><div className="mt-2 flex items-center justify-between text-[9px] uppercase text-white/65"><span>420 m · 6 min</span><button type="button" className="rounded bg-[#6c9aca] px-2 py-1 text-white"><Send size={12} /></button></div></section></div>
    <footer className="flex justify-between border-t border-white/10 px-1 pt-2 text-[9px] uppercase text-white/45"><span>AERO SENSE | BUILT FOR A SAFER TOMORROW</span><span>DETECT | LOCATE | ASSESS | GUIDE | SAVE LIVES</span></footer>
  </div></div>
}

export default DashboardPage
