<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aero_sense_bringup</name>
  <version>0.1.0</version>
  <description>Launch files, configuration and diagnostics for the Aero Sense SAR simulation.</description>
  <maintainer email="codenexusky@gmail.com">kushsaraf</maintainer>
  <license>TODO</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>aero_sense_interfaces</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>aero_sense_description</exec_depend>
  <exec_depend>aero_sense_gazebo</exec_depend>
  <exec_depend>aero_sense_mission</exec_depend>
  <exec_depend>aero_sense_scenario_manager</exec_depend>
  <exec_depend>aero_sense_perception</exec_depend>
  <exec_depend>aero_sense_visualization</exec_depend>

  <test_depend>python3-pytest</test_depend>
  <test_depend>python3-pil</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
