#!/usr/bin/env python3
"""Lay out the disaster world as an Indian residential society: winding asphalt roads, narrow
concrete galis and village dirt tracks, buildings packed along them and facing the street,
electric poles (leaning in the earthquake), parked vehicles, cordons, and a flood with a ragged
shoreline standing in a valley (flood_valley.py). Every building in the earthquake sector is
damaged or collapsed. No casualty (victims.yaml) ends up under anything, except the ones trapped
inside a collapse on purpose, and nothing lands on a hand-placed landmark.

    python3 tools/make_buildings.py src/aero_sense_gazebo/models    # first: footprints come from these
    python3 tools/layout_world.py [--seed 26]

Rewrites, in src/aero_sense_gazebo:
    worlds/aero_sense_disaster.sdf                between the GENERATED markers
    models/aero_sense_roads/meshes/               roads.obj, lanes.obj, tracks.obj
    models/aero_sense_ground/meshes/              ground.obj (grass), earth.obj (the society), dust.obj
                                                  (around collapses), mud.obj (the flood valley)
    models/aero_sense_flood_water/meshes/water.obj
Streets and galis are Catmull-Rom curves through their control points; a casualty lying in one
is one of those points, so the curve passes through it.
"""
import argparse
import math
import random
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np
import yaml

ROOT = Path(__file__).resolve().parent.parent
GAZEBO = ROOT / "src" / "aero_sense_gazebo"
WORLD = GAZEBO / "worlds" / "aero_sense_disaster.sdf"
MODELS = GAZEBO / "models"
VICTIMS = ROOT / "src" / "aero_sense_scenario_manager" / "config" / "victims.yaml"
sys.path.insert(0, str(ROOT / "src" / "aero_sense_perception"))
from aero_sense_perception.structure_map import include_pose, model_footprint  # noqa: E402

import flood_valley  # noqa: E402  (beside this script)
import make_buildings  # noqa: E402

BEGIN, END = "<!-- GENERATED by tools/layout_world.py", "<!-- END GENERATED -->"
BUILDING = "aero_sense_building_"

#: (name, surface, width m, control points)
ROADS = (
    ("spine", "asphalt", 8.0, ((1, -132), (0, -104), (-3, -62), (3, -28), (0, 0), (-3, 38), (4, 72), (0, 106))),
    ("south_avenue", "asphalt", 8.0, ((-206, -1), (-150, 3), (-100, -1), (-50, 2), (0, 0), (60, -3), (120, 2), (206, -1))),
    ("north_avenue", "asphalt", 8.0, ((-206, 101), (-140, 97), (-80, 103), (-20, 98), (40, 102), (110, 97), (206, 100))),
    # through V18, V22, V16, V21, V17 and V19
    ("s1_main_street", "asphalt", 7.0, ((-200, 54), (-175, 50), (-155, 44), (-135, 47), (-116, 52.5), (-95, 50),
                                        (-82, 45), (-70, 46), (-55, 53), (-40, 50), (-20, 44), (0, 47))),
    ("s1_cross_street", "asphalt", 6.5, ((-100, 0), (-105, 18), (-110, 38), (-112, 50), (-109, 64), (-104, 82), (-99, 100))),
    ("gali_west", "lane", 3.5, ((-199, 28), (-176, 21.5), (-156, 31), (-136, 21.5), (-122, 26), (-108, 29))),   # V01, V03, V02
    ("gali_market", "lane", 3.5, ((-62, 1), (-75, 12), (-78, 25), (-80, 38), (-82, 45))),                     # V04
    ("gali_fire_station", "lane", 3.5, ((-146, 45), (-147, 60), (-148, 75), (-143, 88), (-138, 99))),         # V06
    ("gali_mast", "lane", 3.5, ((-22, 45), (-26, 58), (-33, 66), (-45, 78), (-57, 88), (-54, 99))),          # V08, V07
    ("gali_tower", "lane", 3.5, ((-24, 2), (-19, 20), (-12, 40), (-5, 47))),                                 # V05
    ("s2_track_north", "track", 4.0, ((30, 2), (45, 25), (55, 32), (80, 48), (100, 60), (122, 76), (128, 98))),  # V10 on it
    ("s2_track_east", "track", 4.0, ((198, 52), (170, 49), (150, 45), (125, 35), (100, 28), (78, 18), (62, 2))),
)
SURFACES = {  # obj file, header, first z, z step (crossings sit a little apart so none z-fight)
    "asphalt": ("roads.obj", "Asphalt roads", 0.018, 0.0015),
    "lane": ("lanes.obj", "Concrete galis", 0.008, 0.0012),
    "track": ("tracks.obj", "Village dirt tracks", 0.008, 0.0012),
}
#: Sector: plot region (x0, y0, x1, y1), gap between buildings, and how often each building appears.
SECTORS = {
    # the earthquake left nothing whole: every building is damaged or down
    "s1": ((-199.0, 5.0, -5.0, 96.0), 0.25, {
        "damaged_topfloor_rowhouse_3f": 3.0, "damaged_infill_rowhouse_2f": 3.0, "collapsed_pancake_rowhouse": 3.0,
        "damaged_corner_house_3f": 2.0, "damaged_infill_3f": 2.0, "collapsed_pancake_3f": 1.5,
        "collapsed_pancake_2f": 1.5, "damaged_softstorey_4f": 0.6, "collapsed_slumped_4f": 0.4}),
    "s2": ((7.0, 5.0, 197.0, 96.0), 0.8, {
        "rowhouse_2f_orange_shop": 1.5, "rowhouse_2f_teal": 2.0, "house_1f_cream": 4.0, "house_1f_blue": 4.0, "house_2f_pink": 3.0, "house_2f_yellow_shop": 1.0,
        "house_3f_green": 1.0}),
}
#: Casualties trapped inside a collapse on purpose (victims.yaml inside_structure): the building
#: goes round them, with the casualty in the crack make_buildings leaves along +x of the centre.
PINNED = (("V13", "collapsed_pancake_2f", -90.0), ("V14", "collapsed_pancake_3f", 0.0),
          ("V15", "collapsed_pancake_3f", 180.0))
CRACK_OFFSET_M = 2.5
#: Flood casualties above the water (victims.yaml perch) and what they wait on, built round them:
#: a car stranded on the track, a house whose roof terrace they sit or stand on, a house whose
#: first-floor window they lean out of. The house's front (model -y) faces where they look.
PERCHED = (("V10", "hatchback"), ("V11", "house_1f_cream"), ("V12", "house_2f_pink"),
           ("V20", "house_2f_pink"), ("V23", "rowhouse_2f_teal"))
#: Hatchback roof above its wheels (reference hatchback.obj: 61.28 in at 0.0254 m/in).
HATCHBACK_ROOF_M = 1.556
#: Terrace casualties stand this far behind the front of the roof, clear of the stair room at the back.
TERRACE_FROM_FRONT_M = 2.5
#: A window casualty's head clears the wall face by this much, and is this high above the floor:
#: in the window, whose centre make_buildings puts 1.6 m up. Anyone shorter stands on a bed or stool.
HEAD_OUT_OF_WINDOW_M = 0.15
HEAD_IN_WINDOW_M = 1.5
#: Footprint half extents (model x, y) of the reference models the layout has to keep clear of.
LANDMARK_HALF_EXTENTS_M = {
    "collapsed_industrial": (11.6, 10.0), "collapsed_fire_station": (14.0, 9.2),
    "collapsed_police_station": (9.8, 11.1), "radio_tower": (5.9, 6.7), "water_tower": (1.4, 1.4),
    "bus": (1.4, 6.3), "pickup": (1.25, 2.85), "hatchback": (1.05, 2.0), "jersey_barrier": (2.05, 0.4),
    "aero_sense_electric_pole": (0.5, 0.5),
}
VEHICLES = (("s1_bus", "bus", "s1_main_street"), ("s1_pickup_1", "pickup", "s1_cross_street"),
            ("s1_pickup_2", "pickup", "gali_market"), ("s1_hatchback_1", "hatchback", "s1_main_street"),
            ("s1_hatchback_2", "hatchback", "gali_fire_station"), ("s2_bus", "bus", "s2_track_east"),
            ("s2_pickup_1", "pickup", "s2_track_north"), ("s2_hatchback_1", "hatchback", "s2_track_east"))
#: Police cordon across a road, metres in from one of its ends.
CORDONS = (("s1_main_street", -8.0), ("s1_cross_street", 8.0), ("s2_track_north", 8.0))
VICTIM_CLEARANCE_M = 2.0          # a building's footprint stays this far off any casualty
VEHICLE_CLEARANCE_M = 7.0
ROAD_SETBACK_M = 0.3              # nothing built on the road itself
RUBBLE_SPREAD_M = 1.5             # how far a collapse's rubble reaches past its walls (make_buildings)


class Road:
    def __init__(self, name, surface, width, points, rng):
        self.name, self.surface = name, surface
        self.xy, self.s = catmull_rom(points)
        d = np.gradient(self.xy, axis=0)
        self.heading = np.arctan2(d[:, 1], d[:, 0])
        a, b = rng.uniform(0, 6.3), rng.uniform(0, 6.3)
        self.half_width = width / 2 * (1 + 0.07 * np.sin(self.s / 19 + a) + 0.04 * np.sin(self.s / 6.3 + b))

    def frontage(self, s, length, side):
        """Where a plot of this frontage starting at arc length `s` sits on one side of a curving road:
        (midpoint, heading of the chord, outward normal, distance from the chord to the road's edge)."""
        i0, i1 = np.searchsorted(self.s, (s, s + length)).clip(0, len(self.s) - 1)
        a, b = self.xy[i0], self.xy[i1]
        heading = math.atan2(b[1] - a[1], b[0] - a[0])
        normal = side * np.array((-math.sin(heading), math.cos(heading)))
        edge = float(((self.xy[i0:i1 + 1] - a) @ normal + self.half_width[i0:i1 + 1]).max())
        return (a + b) / 2, heading, normal, edge

    def at(self, s):
        i = int(np.clip(np.searchsorted(self.s, s), 0, len(self.s) - 1))
        normal = np.array((-math.sin(self.heading[i]), math.cos(self.heading[i])))
        return self.xy[i], float(self.heading[i]), normal, float(self.half_width[i])


def catmull_rom(points, step=1.0):
    p = [np.array(q, dtype=float) for q in points]
    p = [2 * p[0] - p[1]] + p + [2 * p[-1] - p[-2]]
    out = []
    for i in range(1, len(p) - 2):
        p0, p1, p2, p3 = p[i - 1], p[i], p[i + 1], p[i + 2]
        n = max(2, int(math.ceil(np.linalg.norm(p2 - p1) / step)))
        for t in np.arange(n) / n:
            out.append(0.5 * (2 * p1 + (p2 - p0) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t
                              + (3 * p1 - p0 - 3 * p2 + p3) * t ** 3))
    out.append(p[-2])
    xy = np.array(out)
    return xy, np.concatenate(([0.0], np.cumsum(np.linalg.norm(np.diff(xy, axis=0), axis=1))))


def rotate(yaw, x, y):
    return x * math.cos(yaw) - y * math.sin(yaw), x * math.sin(yaw) + y * math.cos(yaw)


class Box:
    """An oriented footprint: centre, heading and half extents."""

    def __init__(self, x, y, yaw, hx, hy):
        self.x, self.y, self.yaw, self.hx, self.hy = x, y, yaw, hx, hy

    def corners(self, grow=0.0):
        return [(self.x + dx, self.y + dy) for dx, dy in
                (rotate(self.yaw, sx * (self.hx + grow), sy * (self.hy + grow))
                 for sx, sy in ((-1, -1), (1, -1), (1, 1), (-1, 1)))]

    def contains(self, points, grow=0.0):
        """Mask of which (N, 2) points fall inside this box grown by `grow` (scalar or per point)."""
        dx, dy = points[:, 0] - self.x, points[:, 1] - self.y
        c, s = math.cos(self.yaw), math.sin(self.yaw)
        return (np.abs(dx * c + dy * s) < self.hx + grow) & (np.abs(-dx * s + dy * c) < self.hy + grow)

    def overlaps(self, other, gap=0.0):
        reach = math.hypot(self.hx, self.hy) + math.hypot(other.hx, other.hy) + 2 * gap
        if math.hypot(self.x - other.x, self.y - other.y) > reach:
            return False
        a, b = self.corners(gap), other.corners()
        for poly in (a, b):
            for i in range(4):
                (x1, y1), (x2, y2) = poly[i], poly[(i + 1) % 4]
                nx, ny = y2 - y1, x1 - x2
                pa, pb = [nx * x + ny * y for x, y in a], [nx * x + ny * y for x, y in b]
                if max(pa) < min(pb) or max(pb) < min(pa):
                    return False
        return True


class Layout:
    def __init__(self, rng, victims, landmarks, roads, valley):
        self.rng, self.valley = rng, valley
        self.victim_xy = np.array([(v["x"], v["y"]) for v in victims])
        self.obstacles = list(landmarks)
        self.road_xy = np.concatenate([r.xy for r in roads])
        self.road_heading = np.concatenate([r.heading for r in roads])
        self.road_half = np.concatenate([r.half_width for r in roads])
        self.includes, self.collapses = [], []
        self.building_count = 0
        self.footprints = {p.name[len(BUILDING):]: model_footprint(p / "model.sdf")
                           for p in MODELS.glob(BUILDING + "*")}

    def clear(self, box, gap, pinned_victim=None, rubble_m=0.0, on_road=False):
        """Whether a footprint fits. Rubble (the outer `rubble_m` of a damaged building's footprint)
        may spill onto a road or into the neighbour's rubble; it may never cover a casualty. Only a
        collapse pinned round a casualty in the street may stand `on_road`."""
        body = self.body(box, rubble_m)
        if not on_road and body.contains(self.road_xy, self.road_half + ROAD_SETBACK_M).any():
            return False
        near = box.contains(self.victim_xy, VICTIM_CLEARANCE_M)
        if pinned_victim is not None:
            near[pinned_victim] = False
        return not near.any() and not any(body.overlaps(o, gap) for o in self.obstacles)

    @staticmethod
    def body(box, rubble_m):
        return Box(box.x, box.y, box.yaw, max(0.5, box.hx - rubble_m), max(0.5, box.hy - rubble_m))

    def add(self, name, uri, x, y, yaw, box, roll=0.0, pitch=0.0):
        self.obstacles.append(box)
        z = self.valley.height_at(x, y)                    # on the terrain: down in the valley, up on its bank
        self.includes.append(f"    <include><name>{name}</name><pose>{x:.2f} {y:.2f} {z:.2f} {roll:.3f} {pitch:.3f} "
                             f"{yaw:.3f}</pose><uri>model://{uri}</uri></include>")

    def building_box(self, kind, x, y, yaw):
        cx, cy, hx, hy, _ = self.footprints[kind]
        dx, dy = rotate(yaw, cx, cy)
        return Box(x + dx, y + dy, yaw, hx, hy)

    def place_building(self, name, kind, x, y, yaw, gap, pinned_victim=None, on_road=None):
        """Place it if it fits; `name` is a prefix numbered in placing order unless pinned."""
        box = self.building_box(kind, x, y, yaw)
        rubble_m = 0.0 if kind.startswith(("house", "rowhouse", "apartment")) else RUBBLE_SPREAD_M
        on_road = pinned_victim is not None if on_road is None else on_road
        if not self.clear(box, gap, pinned_victim, rubble_m, on_road):
            return False
        if pinned_victim is None:
            self.building_count += 1
            name = f"{name}_{self.building_count}"
        self.add(name, BUILDING + kind, x, y, yaw, self.body(box, rubble_m))
        if not kind.startswith(("house", "rowhouse", "apartment")):
            self.collapses.append((box.x, box.y, max(box.hx, box.hy)))
        return True

    def pick(self, weights, surface):
        """A building kind; shops cluster on the asphalt roads and thin out in the galis."""
        kinds = list(weights)
        shop_scale = {"asphalt": 3.0, "lane": 0.2, "track": 0.2}.get(surface, 1.0)
        return self.rng.choices(kinds, [weights[k] * (shop_scale if k.endswith("_shop") else 1.0) for k in kinds])[0]


def in_region(box, region):
    x0, y0, x1, y1 = region
    return all(x0 <= x <= x1 and y0 <= y <= y1 for x, y in box.corners())


def distances(points, x, y):
    return np.hypot(points[:, 0] - x, points[:, 1] - y)


def place_pinned(layout, victims):
    by_id = {v["id"]: i for i, v in enumerate(victims)}
    for vid, kind, yaw_deg in PINNED:
        i, yaw = by_id[vid], math.radians(yaw_deg)
        dx, dy = rotate(yaw, CRACK_OFFSET_M, 0.0)
        x, y = victims[i]["x"] - dx, victims[i]["y"] - dy
        if not layout.place_building(f"s1_trapped_{vid.lower()}", kind, x, y, yaw, 0.3, pinned_victim=i):
            raise SystemExit(f"{vid}: its collapse overlaps a landmark or another casualty")


def intact_size(kind):
    """(width, depth, floors) of an intact make_buildings kind."""
    return next((w, d, floors) for name, w, d, floors, _, _ in make_buildings.INTACT if name == kind)


def perch_spot(kind: str, perch: str, person: dict) -> tuple:
    """Where someone on a perch stands: the (x, y) offset in the perch model's frame and the floor
    height above its base. `person` is their mesh's people.yaml entry. Also used by
    ml/make_dataset.py, so the dataset's perched people stand exactly as the scenario's do."""
    if perch == "car_roof":
        return (0.0, 0.0), HATCHBACK_ROOF_M
    w, d, floors = intact_size(kind)
    if perch == "terrace":
        return (0.0, -d / 2 + TERRACE_FROM_FRONT_M), make_buildings.PLINTH_M + floors * make_buildings.FLOOR_M + 0.02
    head_x, _, head_z = person["points"]["head"]
    inside = max(0.1, head_x - HEAD_OUT_OF_WINDOW_M)
    step_up = max(0.0, HEAD_IN_WINDOW_M - head_z)
    return (make_buildings.openings(w)[0], -d / 2 + inside), make_buildings.PLINTH_M + make_buildings.FLOOR_M + step_up


def place_perched(layout, victims):
    """Build what each flood casualty waits on, and check they stand on it: their z must be the
    terrain under it plus its roof or floor height, so nobody floats or stands in the water."""
    by_id = {v["id"]: i for i, v in enumerate(victims)}
    people = yaml.safe_load((VICTIMS.parent / "people.yaml").read_text())
    wrong = []
    for vid, kind in PERCHED:
        i = by_id[vid]
        v = victims[i]
        facing = math.radians(v.get("yaw_deg", 0.0))
        offset, height = perch_spot(kind, v["perch"], people[f"{v['character']}_{v['pose']}"])
        if v["perch"] == "car_roof":
            yaw = facing - math.pi / 2                                  # the models run along their y
            hx, hy = LANDMARK_HALF_EXTENTS_M[kind]
            layout.add(f"s2_stranded_{vid.lower()}", kind, v["x"], v["y"], yaw, Box(v["x"], v["y"], yaw, hx, hy))
            floor = layout.valley.height_at(v["x"], v["y"]) + height
        else:
            yaw = facing + math.pi / 2                                  # the front, model -y, faces where they look
            dx, dy = rotate(yaw, *offset)
            x, y = v["x"] - dx, v["y"] - dy
            if not layout.place_building(f"s2_refuge_{vid.lower()}", kind, x, y, yaw, 0.3, pinned_victim=i, on_road=False):
                raise SystemExit(f"{vid}: its {kind} overlaps a road, a landmark or another casualty; move it in victims.yaml")
            floor = layout.valley.height_at(x, y) + height
        if abs(floor - float(v.get("z", 0.0))) > 0.02:
            wrong.append(f"{vid} z: {floor:.2f}")
    if wrong:
        raise SystemExit("perched casualties must stand on their perch; set in victims.yaml: " + ", ".join(wrong))


def place_vehicles(layout, roads):
    rng = layout.rng
    for name, uri, road_name in VEHICLES:
        road, region = roads[road_name], SECTORS[name[:2]][0]
        hx, hy = LANDMARK_HALF_EXTENTS_M[uri]
        for _ in range(400):
            (px, py), heading, normal, half = road.at(rng.uniform(5, road.s[-1] - 5))
            if not (region[0] <= px <= region[2] and region[1] <= py <= region[3]):
                continue
            side = rng.choice((-1, 1)) * (half * 0.4 if road.surface == "asphalt" else 0.0)
            x, y = px + normal[0] * side, py + normal[1] * side
            skew = rng.gauss(0, math.radians(12 if name.startswith("s1") else 4))
            yaw = heading - math.pi / 2 + rng.choice((0, math.pi)) + skew     # the models run along their y
            box = Box(x, y, yaw, hx, hy)
            if distances(layout.victim_xy, x, y).min() >= VEHICLE_CLEARANCE_M and \
                    not any(box.overlaps(o, 0.5) for o in layout.obstacles):
                layout.add(name, uri, x, y, yaw, box)
                break
        else:
            print(f"warning: no room for {name} on {road_name}")


def place_cordons(layout, roads):
    for road_name, from_end in CORDONS:
        road = roads[road_name]
        (px, py), heading, normal, half = road.at(from_end if from_end > 0 else road.s[-1] + from_end)
        for k, side in enumerate((-0.55, 0.55)):
            x, y = px + normal[0] * side * half, py + normal[1] * side * half
            yaw = heading + math.pi / 2
            layout.add(f"cordon_{road_name}_{k + 1}", "jersey_barrier", x, y, yaw,
                       Box(x, y, yaw, *LANDMARK_HALF_EXTENTS_M["jersey_barrier"]))


def place_frontage(layout, roads):
    """Buildings along both sides of every street, fronts to the road, the odd plot left empty."""
    rng = layout.rng
    for road in roads.values():
        for side in (1, -1):
            s = rng.uniform(0, 6)
            while s < road.s[-1]:
                (px, py), *_ = road.at(s)
                sector = "s1" if px < 0 else "s2"
                region, gap, weights = SECTORS[sector]
                if rng.random() < 0.07:
                    s += rng.uniform(8, 15)
                    continue
                placed = None
                for _ in range(3):                    # a smaller building may fit where the first did not
                    kind = layout.pick(weights, road.surface)
                    cx, cy, hx, hy, _ = layout.footprints[kind]
                    (px, py), heading, normal, edge = road.frontage(s, 2 * hx, side)
                    yaw = (heading if side == 1 else heading + math.pi) + \
                        rng.gauss(0, math.radians(5 if kind.startswith("collapsed") else 1.5))
                    setback = rng.uniform(0.6, 2.4) if road.surface == "asphalt" else rng.uniform(0.5, 1.2)
                    fx, fy = px + normal[0] * (edge + setback + hy), py + normal[1] * (edge + setback + hy)
                    dx, dy = rotate(yaw, cx, cy)
                    x, y = fx - dx, fy - dy
                    if in_region(layout.building_box(kind, x, y, yaw), region) and \
                            layout.place_building(f"{sector}_building", kind, x, y, yaw, gap):
                        placed = hx
                        break
                if placed is not None:
                    s += 2 * placed + (rng.uniform(0.25, 0.6) if placed < 4 else rng.uniform(0.4, 2.2))
                else:
                    s += 1.5


#: Big blocks placed before the street fronts fill every gap: (sector, kinds, how many, tries).
ANCHORS = (("s1", ("collapsed_toppled_5f",), 1, 4000),
           ("s1", ("damaged_softstorey_4f",), 3, 3000),
           ("s1", ("collapsed_slumped_4f",), 2, 3000))


def place_infill(layout, sectors, limit=None, tries=4000):
    """Buildings at random spots, facing the nearest road, until `limit` fit or the tries run out."""
    rng = layout.rng
    for sector, weights in sectors.items():
        region, gap, _ = SECTORS[sector]
        placed = 0
        for _ in range(tries):
            if limit is not None and placed >= limit:
                break
            x, y = rng.uniform(region[0], region[2]), rng.uniform(region[1], region[3])
            i = int(np.argmin(distances(layout.road_xy, x, y)))
            heading = float(layout.road_heading[i])
            rx, ry = layout.road_xy[i]
            left = -math.sin(heading) * (x - rx) + math.cos(heading) * (y - ry) > 0
            yaw = (heading if left else heading + math.pi) + rng.gauss(0, math.radians(5))
            kind = layout.pick(weights, "infill")
            if in_region(layout.building_box(kind, x, y, yaw), region) and \
                    layout.place_building(f"{sector}_building", kind, x, y, yaw, gap):
                placed += 1


def place_poles(layout, roads):
    rng, count = layout.rng, 0
    for road in roads.values():
        if road.surface != "asphalt":
            continue
        s = rng.uniform(5, 15)
        while s < road.s[-1]:
            (px, py), heading, normal, half = road.at(s)
            s += rng.uniform(26, 36)
            x, y = px + normal[0] * (half + 0.9), py + normal[1] * (half + 0.9)
            if not (-200 <= x <= 200 and -125 <= y <= 104) or math.hypot(x, y + 110) < 20:   # clear of the pad
                continue
            box = Box(x, y, heading, *LANDMARK_HALF_EXTENTS_M["aero_sense_electric_pole"])
            if distances(layout.victim_xy, x, y).min() < 3.0 or any(box.overlaps(o) for o in layout.obstacles):
                continue
            quake = x < 0 and 0 < y < 100
            lean = (rng.uniform(-0.22, 0.22), rng.uniform(-0.22, 0.22)) if quake and rng.random() < 0.35 else (0.0, 0.0)
            count += 1
            layout.add(f"pole_{count}", "aero_sense_electric_pole", x, y, heading, box, *lean)


def write_strips(roads, valley):
    by_surface = {}
    for road in roads.values():
        by_surface.setdefault(road.surface, []).append(road)
    for surface, (filename, header, z0, dz) in SURFACES.items():
        lines = [f"# {header} (world coordinates), generated by tools/layout_world.py: one strip per",
                 "# road along its curve, its width wandering; UVs tile every 8 m.", "vn 0 0 1"]
        base = 1
        for k, road in enumerate(by_surface.get(surface, [])):
            z = z0 + k * dz
            normal = np.stack((-np.sin(road.heading), np.cos(road.heading)), axis=1)
            for side in (-1, 1):
                edge = road.xy + side * normal * road.half_width[:, None]
                ground = z + valley.height(edge)               # tracks run over the bank and down into the valley
                for (x, y), s, h, height in zip(edge, road.s, road.half_width, ground):
                    lines += [f"v {x:.2f} {y:.2f} {height:.4f}", f"vt {side * h / 8:.3f} {s / 8:.3f}"]
            n = len(road.s)
            for j in range(n - 1):
                r0, r1, l0, l1 = base + j, base + j + 1, base + n + j, base + n + j + 1
                lines += [f"f {r0}/{r0}/1 {r1}/{r1}/1 {l1}/{l1}/1", f"f {r0}/{r0}/1 {l1}/{l1}/1 {l0}/{l0}/1"]
            base += 2 * n
        (MODELS / "aero_sense_roads" / "meshes" / filename).write_text("\n".join(lines) + "\n")


def blob(lines, base, cx, cy, radius, z, rng, k=40):
    phases = [rng.uniform(0, 6.3) for _ in range(3)]
    lines += [f"v {cx:.2f} {cy:.2f} {z:.4f}", f"vt {cx / 6:.3f} {cy / 6:.3f}"]
    for i in range(k):
        t = 2 * math.pi * i / k
        r = radius * (1 + 0.22 * math.sin(2 * t + phases[0]) + 0.12 * math.sin(5 * t + phases[1])
                      + 0.06 * math.sin(11 * t + phases[2]))
        x, y = cx + r * math.cos(t), cy + r * math.sin(t)
        lines += [f"v {x:.2f} {y:.2f} {z:.4f}", f"vt {x / 6:.3f} {y / 6:.3f}"]
    for i in range(k):
        a, b = base + 1 + i, base + 1 + (i + 1) % k
        lines.append(f"f {base}/{base}/1 {a}/{a}/1 {b}/{b}/1")
    return base + k + 1


def write_dust(layout, landmark_patches, rng):
    centres = [(x, y, r * 1.15) for x, y, r in layout.collapses if x < 0] + landmark_patches
    lines = ["# Concrete dust around S1's collapses (world coordinates), generated by tools/layout_world.py:",
             "# ragged blobs, each 0.6 mm above the last so none z-fight; galis start at 8 mm.", "vn 0 0 1"]
    base = 1
    for i, (x, y, r) in enumerate(centres[:10]):
        base = blob(lines, base, x, y, r * rng.uniform(0.9, 1.2), 0.002 + 0.0006 * i, rng)
    (MODELS / "aero_sense_ground" / "meshes" / "dust.obj").write_text("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--seed", type=int, default=26)
    args = parser.parse_args()
    rng = random.Random(args.seed)
    victims = yaml.safe_load(VICTIMS.read_text())["victims"]
    text = WORLD.read_text()
    start, stop = text.index(BEGIN), text.index(END)
    head = text[:start] + text[start:].split("\n", 1)[0] + "\n"
    landmarks, landmark_patches = [], []
    for include in ET.fromstring(text[:start] + text[stop:]).iter("include"):
        uri = (include.findtext("uri") or "")[len("model://"):]
        if uri in LANDMARK_HALF_EXTENTS_M:
            x, y, yaw = include_pose(include)
            landmarks.append(Box(x, y, yaw, *LANDMARK_HALF_EXTENTS_M[uri]))
            if uri.startswith("collapsed_"):
                landmark_patches.append((x, y, max(LANDMARK_HALF_EXTENTS_M[uri]) * 1.3))
    roads = {name: Road(name, surface, width, points, rng) for name, surface, width, points in ROADS}
    for name, road in roads.items():
        for box in landmarks:
            if box.contains(road.xy, road.half_width).any():
                print(f"note: {name} brushes the landmark at ({box.x:.0f}, {box.y:.0f})")
    valley = flood_valley.Valley(random.Random(args.seed))    # its own stream: layout changes leave the shore be
    valley.check(victims)
    layout = Layout(rng, victims, landmarks, list(roads.values()), valley)
    place_pinned(layout, victims)
    place_perched(layout, victims)
    place_vehicles(layout, roads)
    place_cordons(layout, roads)
    for sector, kinds, count, tries in ANCHORS:
        place_infill(layout, {sector: dict.fromkeys(kinds, 1.0)}, limit=count, tries=tries)
    place_frontage(layout, roads)
    place_infill(layout, {sector: weights for sector, (_, _, weights) in SECTORS.items()})
    place_poles(layout, roads)
    buildings = [line for line in layout.includes if BUILDING in line]
    print(f"{len(buildings)} buildings ({sum('collapsed' in b for b in buildings)} collapsed, "
          f"{sum('damaged' in b for b in buildings)} damaged), "
          f"{sum('electric_pole' in line for line in layout.includes)} poles")
    WORLD.write_text(head + "\n".join(layout.includes) + "\n    " + text[stop:])
    write_strips(roads, valley)
    write_dust(layout, landmark_patches, rng)
    flood_valley.write_meshes(MODELS, valley, rng)


if __name__ == "__main__":
    main()
