#!/usr/bin/env python3
"""Generate the landslide sector's terrain mesh.

    python3 tools/make_terrain.py

Gazebo's <heightmap> renders for physics but not in sensor cameras, so the ridge is a mesh:
meshes are what the RGB, depth, thermal and LiDAR paths all agree on. Written as two OBJs, both
committed because they are world inputs rather than build artefacts:

  terrain_slope.obj      visual, 2 m grid: the grassy lower slopes
  terrain_scar.obj       visual, 2 m grid: the bare upper face and failure scar
                         (two files rather than two groups in one: gz's OBJ loader splits
                         submeshes by material, not by group name)
  terrain_collision.obj   the same surface at 8 m, because mesh collision costs per triangle

The land rises northwards from zero at its south edge (meeting the flat city plain exactly),
crests, and carries a gouge where the slope failed, with a debris fan spread over the toe.
"""
import math
from pathlib import Path

import numpy as np

MODEL = Path(__file__).resolve().parents[1] / "src/aero_sense_gazebo/models/aero_sense_terrain"
SPAN_M = 200.0
RELIEF_M = 25.0
VISUAL_STEP_M, COLLISION_STEP_M = 2.0, 8.0
#: Texture repeat, per surface: grass reads well at 8 m, rubble needs a finer tile or it looks
#: like paving slabs from the air.
GRASS_TILE_M, RUBBLE_TILE_M = 8.0, 3.0
#: Grass gives way to bare rubble across this band rather than at one height: the changeover is
#: dithered through it, so the boundary breaks up instead of stepping along the mesh grid.
SCAR_BAND_M = (5.0, 9.0)
CREST_AT = 0.72
SLIDE_CENTRE_X, SLIDE_WIDTH = 0.42, 0.13


def height(east: np.ndarray, north: np.ndarray) -> np.ndarray:
    """Height in metres for normalised (0..1) positions across and up the sector."""
    ridge = np.clip(north / CREST_AT, 0.0, 1.0) ** 1.6
    ridge = ridge * (0.85 + 0.15 * np.cos(2 * math.pi * east * 1.5))
    scar = 0.35 * np.exp(-(((east - SLIDE_CENTRE_X) / SLIDE_WIDTH) ** 2)) \
        * np.clip(np.sin(math.pi * np.clip(north / CREST_AT, 0, 1)), 0, 1) ** 0.7
    fan = 0.06 * np.exp(-(((east - SLIDE_CENTRE_X) / (SLIDE_WIDTH * 2.4)) ** 2)) \
        * np.exp(-((north / 0.18) ** 2))
    rough = 0.02 * np.sin(east * 37.0) * np.sin(north * 41.0)
    return np.clip(ridge - scar + fan + rough, 0.0, 1.0) * RELIEF_M


def grid(step_m: float):
    count = int(SPAN_M / step_m) + 1
    axis = np.linspace(-SPAN_M / 2, SPAN_M / 2, count)
    x, y = np.meshgrid(axis, axis, indexing="ij")
    normalised_east = (x + SPAN_M / 2) / SPAN_M
    normalised_north = (y + SPAN_M / 2) / SPAN_M
    return x, y, height(normalised_east, normalised_north)


def scar_fraction(height_m: float) -> float:
    low, high = SCAR_BAND_M
    t = np.clip((height_m - low) / (high - low), 0.0, 1.0)
    return float(t * t * (3 - 2 * t))          # smoothstep


def is_scar(height_m: float, i: int, j: int) -> bool:
    """Dither the changeover deterministically, so the same mesh comes out of every run."""
    noise = ((i * 73856093) ^ (j * 19349663)) % 1000 / 1000.0
    return scar_fraction(height_m) > noise


def write_obj(path: Path, step_m: float, keep=None, tile_m: float = GRASS_TILE_M):
    x, y, z = grid(step_m)
    count = x.shape[0]
    lines = [f"# Aero Sense landslide ridge: {SPAN_M:.0f} x {SPAN_M:.0f} m, {step_m:.0f} m grid.",
             "# Generated by tools/make_terrain.py - edit the generator, not this file."]
    for i in range(count):
        for j in range(count):
            lines.append(f"v {x[i, j]:.3f} {y[i, j]:.3f} {z[i, j]:.3f}")
    for i in range(count):
        for j in range(count):
            lines.append(f"vt {x[i, j] / tile_m:.4f} {y[i, j] / tile_m:.4f}")
    normals = surface_normals(x, y, z)
    for i in range(count):
        for j in range(count):
            n = normals[i, j]
            lines.append(f"vn {n[0]:.4f} {n[1]:.4f} {n[2]:.4f}")

    def index(i, j):
        return i * count + j + 1

    faces = []
    for i in range(count - 1):
        for j in range(count - 1):
            corners = [(i, j), (i + 1, j), (i + 1, j + 1), (i, j + 1)]
            highest = max(z[a, b] for a, b in corners)
            if keep is not None and (keep == "scar") != is_scar(highest, i, j):
                continue
            a, b, c, d = (index(*corner) for corner in corners)
            faces.append(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}")
            faces.append(f"f {a}/{a}/{a} {c}/{c}/{c} {d}/{d}/{d}")
    path.write_text("\n".join(lines + faces) + "\n")
    return count, len(faces)


def surface_normals(x, y, z):
    """Central-difference normals, so the slope shades smoothly instead of faceting."""
    dz_dx, dz_dy = np.gradient(z, x[:, 0], y[0, :])
    normals = np.stack([-dz_dx, -dz_dy, np.ones_like(z)], axis=-1)
    return normals / np.linalg.norm(normals, axis=-1, keepdims=True)


def main():
    meshes = MODEL / "meshes"
    meshes.mkdir(parents=True, exist_ok=True)
    for path, step, keep, tile in ((meshes / "terrain_slope.obj", VISUAL_STEP_M, "slope", GRASS_TILE_M),
                                   (meshes / "terrain_scar.obj", VISUAL_STEP_M, "scar", RUBBLE_TILE_M),
                                   (meshes / "terrain_collision.obj", COLLISION_STEP_M, None, GRASS_TILE_M)):
        count, faces = write_obj(path, step, keep, tile)
        print(f"{path.name}: {count}x{count} vertices, {faces} faces")


if __name__ == "__main__":
    main()
